#!/bin/bash
#install Persepolis Download Manager
clear screen
echo "############################################################"
echo "#### Welcome to Persepolis Download Manager installation ###"
echo "############################################################"

user=$HOME

program_path="$user/.persepolis_download_manager_terminal"
install_path=`pwd`
echo "mkdir  $program_path"
mkdir  $program_path >/dev/null 2>&1
echo "cp -R -f $install_path/files/* $program_path"
cp -R -f $install_path/files/* $program_path
chmod +x $program_path/pdmt
chmod +x $program_path/persepolisdm
chmod +x $program_path/PDMT
chmod +x $program_path/PDM
chmod +x $program_path/pdmt_flashgot_gtk
chmod +x $program_path/pdm_flashgot_gtk
chmod +x $program_path/pdm_zenity
chmod +x $program_path/Persepolis.desktop
if [ ! -f ~/.Xresources ];then
cp -R -f ~/.persepolis_download_manager_terminal/Xresources  ~/.Xresources
xrdb -merge ~/.Xresources
fi

echo "sudo  mv -f $program_path/pdmt /usr/bin"
echo "sudo  mv -f $program_path/Persepolis.desktop /usr/share/applications"
sudo  mv -f $program_path/pdmt /usr/bin
sudo  mv -f $program_path/persepolisdm /usr/bin
sudo mkdir /usr/share/persepolisdm
sudo mkdir /usr/share/persepolisdm/icon
sudo  mv -f $program_path/icon.png /usr/share/persepolisdm/icon
sudo  mv -f $program_path/icon_circle.png /usr/share/persepolisdm/icon
sudo  mv -f $program_path/pdmt.1.gz /usr/share/man/man1/pdmt.1.gz
sudo  mv -f $program_path/Persepolis.desktop /usr/share/applications
if [ "$?" -eq "0" ]
   then
      echo "Installation compeleted"
   else
       echo "Installation Failed!"
fi
exit
