#!/bin/bash
#uninstall PDMT

home_env=$(env | grep -e HOME )
home_env_num=$(echo "$home_env" | grep ^ | wc -l)
for iiiii in `seq 1 $home_env_num`;
	do
          home_env_line=$(echo "$home_env" | grep -e HOME | awk -F= '{ print $1 }'| head -$iiiii)
          if [ "$home_env_line" = "HOME" ]
              then
                user=$(echo "$home_env"| grep -e HOME |  awk -F= '{ print $2 }' | head -$iiiii)
          fi           
done
if [ "$user" = "" ]
   then
       echo "Uninstallation faild!can not find home folder"
       exit
fi
program_path="$user/.persian_download_manager_terminal"
rm -f -r $program_path
sudo  rm -f /usr/bin/pdmt
if [ "$?" -eq "0" ]
   then
       echo "Uninstallation compeleted"
fi
exit
