#!/bin/bash
download_type_form () {
download_type=`zenity --list --radiolist --title="PDMT" --text="Please select type of Download" --hide-column=2 --column="" --column="ID" --column="type" TRUE "1" "Single File" FALSE "2" "Download Queue" FALSE "3" "About PDMT"`
if [ $? -eq 1 ]
   then
       exit
fi
case "$download_type" in
      1)
	link=`zenity --entry --title="PDMT" --text="Please enter download link"`
        if [ $? -eq 1 ]
           then
           	download_type_form
        fi
        
        ;;
      2)
        zenity --question --title="PDMT"  --ok-label="Continue" --text="Put your links in a Text file,in separate lines(no space between lines)\nand then click Continue"
        if [ $? -eq 1 ]
           then
           	download_type_form
        fi
	my_file=`zenity --file-selection --title="PDMT" `
        if [ $? -eq 1 ]
           then
           	download_type_form
        fi
	;;
	3)
        zenity --text-info --title="PDMT" --filename="$user/.persepolis_download_manager_terminal/about.txt"
	download_type_form
esac
}

download_form() {

download_info=`zenity --forms  --text="Enter Download options \n (If you don't use any options,leave the fields empty!)" --title="PDMT" --add-entry="Proxy IP(Host):"  --add-entry="Proxy Port:" --add-entry="Proxy UserName:" --add-password="Proxy PassWord:" --add-entry="Download UserName:" --add-password="Download PassWord:"  --add-entry="Start Time(24 hour format):" --add-entry="End Time(24 hour format):"  --add-list="What should PDMT do after Download?" --list-values="nothing|shutdown|hibernate|suspend"`
if [ $? -eq 1 ]
   then
       exit
fi
echo "$download_info"
ip=$(echo "$download_info" | awk -F"|" '{ print $1 }')
if [ "$ip" = "" ]
   then
       ip="chroniccoughallergies"
fi       
port=$(echo "$download_info" | awk -F"|" '{ print $2 }')
if [ "$port" = "" ]
   then
       port="chroniccoughallergies"
fi       

proxy_user=$(echo "$download_info" | awk -F"|" '{ print $3 }')
if [ "$proxy_user" = "" ]
   then
       proxy_user="chroniccoughallergies"
fi       
proxy_pass=$(echo "$download_info" | awk -F"|" '{ print $4 }')
if [ "$proxy_pass" = "" ]
   then
       proxy_pass="chroniccoughallergies"
fi       
download_user=$(echo "$download_info" | awk -F"|" '{ print $5 }')
if [ "$download_user" = "" ]
   then
       download_user="chroniccoughallergies"
fi       
download_pass=$(echo "$download_info" | awk -F"|" '{ print $6 }')
if [ "$download_pass" = "" ]
   then
       download_pass="chroniccoughallergies"
fi       
start_time=$(echo "$download_info" | awk -F"|" '{ print $7 }')
if [ "$start_time" = "" ]
   then
       start_time="chroniccoughallergies"
fi       
end_time=$(echo "$download_info" | awk -F"|" '{ print $8 }')
if [ "$end_time" = "" ]
   then
       end_time="chroniccoughallergies"
fi       

do_after_download=$(echo "$download_info" | awk -F"|" '{ print $9 }')

case "$do_after_download" in
      "shutdown" | "hibernate" | "suspend" )
      do_after="1"
      ;;
      * )
      do_after="2"
      password_input="chroniccoughallergies"
      ;;
      
esac

if [ "$do_after" -eq "1" ]
   then
       password_input=`zenity --forms  --text="Please enter your ROOT password" --title="PDMT" --add-password="Password : "  `
       if [ $? -eq 1 ]
          then
              exit
       fi
       echo $password_input |sudo -S whoami
       ss=$?
       while [ $ss -ne 0 ]
              do
              password_input=`zenity --forms  --text="Wrong password! Try again!" --title="PDMT" --add-password="Password : "`
              if [ $? -eq 1 ]
                then
                   exit
              fi
              echo $password_input |sudo -S whoami
              ss=$?
              done
fi
}

user=$HOME
clipboard=$(xclip -o -sel clip|awk '/tp:\/\// {print $0}')
if [ "$clipboard" != "" ]
   	then
       		link=`zenity --entry --title="PDMT" --text="Enter Download Link Please!" --entry-text="$clipboard"`
       		if [ $? -eq 1 ]
           		then
           			download_type_form
           		else
           			download_type=1
       		fi  
	else
		           	download_type_form
fi 

download_form

for terminal in $TERMINAL x-terminal-emulator gnome-terminal xfce4-terminal lxterminal konsole mate-terminal urxvt rxvt terminator Eterm aterm roxterm termite xterm ; do
    if command -v $terminal > /dev/null 2>&1; then
        break
    fi
done 

case "$download_type" in
			1)
			  $terminal -e pdmt -l "$link" -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -d "$do_after_download" -w "$password_input" 
			  a=$?
			;;
			*)  
			  $terminal -e pdmt -f "$my_file" -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -d "$do_after_download" -w "$password_input" 
			  a=$?		
			;;
esac

			
if [ "$a" != "0" ] && [ "$a" != "255" ]
    then
	case "$download_type" in
			1)
			  xterm -e pdmt -l "$link" -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -d "$do_after_download" -w "$password_input" 
			;;
			*)  
			  xterm -e pdmt -f "$my_file" -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -d "$do_after_download" -w "$password_input" 
			;;
	esac			
    	
fi        
exit       
