#!/bin/bash
#flashgot_status=0 ready , flashgot_status=1 not ready
link="$1"
user=$HOME
temp_path="$user/.persian_download_manager_terminal/temp"
mkdir $temp_path       >/dev/null 2>&1
flashgot_function() {

download_info=`zenity --forms  --text="Enter Download options \n (If you don't use any option,leave the field empty!)" --title="PDMT" --add-entry="Proxy IP(Host):"  --add-entry="Proxy Port:" --add-entry="Proxy UserName:" --add-password="Proxy PassWord:" --add-entry="Download UserName:" --add-password="Download PassWord:"  --add-entry="Start Time(24 hour format):" --add-entry="End Time(24 hour format):" --add-entry="Reconnecting(yes/no) , default is no"  --add-list="What does PDMT do after Download?" --list-values="nothing|shutdown|hibernate|suspend"`
if [ $? -eq 1 ]
   then
       exit
fi
echo "$download_info"
ip=$(echo "$download_info" | awk -F"|" '{ print $1 }')
if [ "$ip" = "" ]
   then
       ip="chroniccoughallergies"
fi       
port=$(echo "$download_info" | awk -F"|" '{ print $2 }')
if [ "$port" = "" ]
   then
       port="chroniccoughallergies"
fi       

proxy_user=$(echo "$download_info" | awk -F"|" '{ print $3 }')
if [ "$proxy_user" = "" ]
   then
       proxy_user="chroniccoughallergies"
fi       
proxy_pass=$(echo "$download_info" | awk -F"|" '{ print $4 }')
if [ "$proxy_pass" = "" ]
   then
       proxy_pass="chroniccoughallergies"
fi       
download_user=$(echo "$download_info" | awk -F"|" '{ print $5 }')
if [ "$download_user" = "" ]
   then
       download_user="chroniccoughallergies"
fi       
download_pass=$(echo "$download_info" | awk -F"|" '{ print $6 }')
if [ "$download_pass" = "" ]
   then
       download_pass="chroniccoughallergies"
fi       
start_time=$(echo "$download_info" | awk -F"|" '{ print $7 }')
if [ "$start_time" = "" ]
   then
       start_time="chroniccoughallergies"
fi       
end_time=$(echo "$download_info" | awk -F"|" '{ print $8 }')
if [ "$end_time" = "" ]
   then
       end_time="chroniccoughallergies"
fi       

reconnecting_ability=$(echo "$download_info" | awk -F"|" '{ print $9 }')
if [ "$reconnecting_ability" = "" ]
   then
       reconnecting_ability="chroniccoughallergies"
fi       


do_after_download=$(echo "$download_info" | awk -F"|" '{ print $10 }')

case "$do_after_download" in
      "shutdown" | "hibernate" | "suspend" )
      do_after="1"
      ;;
      * )
      do_after="2"
      password_input="chroniccoughallergies"
      ;;
      
esac

if [ "$do_after" -eq "1" ]
   then
       password_input=`zenity --forms  --text="Please enter your ROOT password" --title="PDMT" --add-password="Password : "  `
       if [ $? -eq 1 ]
          then
              exit
       fi
       echo $password_input |sudo -S whoami
       ss=$?
       while [ $ss -ne 0 ]
              do
              password_input=`zenity --forms  --text="Wrong password! Try again!" --title="PDMT" --add-password="Password : "`
              if [ $? -eq 1 ]
                then
                   exit
              fi
              echo $password_input |sudo -S whoami
              ss=$?
              done
fi
}

temp_path="$user/.persian_download_manager_terminal/temp"

flashgot_status=$(cat $temp_path/flashgot.txt ) 

if [ "$flashgot_status" != "1" ]
   then
       echo "1" > $temp_path/flashgot.txt
       echo "$link" > $temp_path/flashgot_queue.txt
       sleep 2
       echo "0" > $temp_path/flashgot.txt
       flashgot_function
   else
       echo "$link" >> $temp_path/flashgot_queue.txt
       exit
fi 

for terminal in $TERMINAL x-terminal-emulator gnome-terminal xfce4-terminal lxterminal konsole mate-terminal urxvt rxvt terminator Eterm aterm roxterm termite xterm ; do
    if command -v $terminal > /dev/null 2>&1; then
        break
    fi
done  

flashgot_line=$(cat $temp_path/flashgot.txt|wc -l)
case "$flashgot_line" in
			1)
			  $terminal -e pdmt -l "$link" -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -r "$reconnecting_ability" -d "$do_after_download" -w "$password_input" 
			  a=$?
			;;
			*)  
			  $terminal -e pdmt -f $temp_path/flashgot_queue.txt -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -r "$reconnecting_ability" -d "$do_after_download" -w "$password_input" 
			  a=$?		
			;;
esac

			
if [ "$a" != "0" ] && [ "$a" != "255" ]
    then
	case "$flashgot_line" in
			1)
			  xterm -e pdmt -l "$link" -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -r "$reconnecting_ability" -d "$do_after_download" -w "$password_input" 
			;;
			*)  
			  xterm -e pdmt -f $temp_path/flashgot_queue.txt -i "$ip" -p "$port" -u "$proxy_user" -a "$proxy_pass" -j "$download_user" -k "$download_pass" -s "$start_time" -e "$end_time" -r "$reconnecting_ability" -d "$do_after_download" -w "$password_input" 
			;;
	esac			
    	
fi        
exit       
