#!/bin/bash
#flashgot_status=0 ready , flashgot_status=1 not ready
flashgot_function() {

download_info=`zenity --forms  --text="Enter Download options \n (If you don't use any options,leave the fields empty!)" --title="PDMT" --add-entry="Proxy IP(Host):"  --add-entry="Proxy Port:" --add-entry="Proxy UserName:" --add-password="Proxy PassWord:" --add-entry="Download UserName:" --add-password="Download PassWord:"  --add-entry="Start Time(24 hour format):" --add-entry="End Time(24 hour format):"  --add-entry="Number of Connections:(default and maximum is 16)" --add-list="What should PDMT do after Download?" --list-values="nothing|shutdown|hibernate|suspend"`
if [ $? -eq 1 ]
   then
       exit
fi
echo "$download_info"
ip=$(echo "$download_info" | awk -F"|" '{ print $1 }')
port=$(echo "$download_info" | awk -F"|" '{ print $2 }')
proxy_user=$(echo "$download_info" | awk -F"|" '{ print $3 }')
proxy_pass=$(echo "$download_info" | awk -F"|" '{ print $4 }')
download_user=$(echo "$download_info" | awk -F"|" '{ print $5 }')
download_pass=$(echo "$download_info" | awk -F"|" '{ print $6 }')
start_time=$(echo "$download_info" | awk -F"|" '{ print $7 }')
end_time=$(echo "$download_info" | awk -F"|" '{ print $8 }')
maximum_connections=$(echo "$download_info" | awk -F"|" '{ print $9 }')
do_after_download=$(echo "$download_info" | awk -F"|" '{ print $10 }')

case "$do_after_download" in
      "shutdown" | "hibernate" | "suspend" )
      do_after="1"
      ;;
      * )
      do_after="2"
      ;;
      
esac

if [ "$do_after" -eq "1" ]
   then
       password_input=`zenity --forms  --text="Please enter your ROOT password" --title="PDMT" --add-password="Password : "  `
       if [ $? -eq 1 ]
          then
              exit
       fi
       echo $password_input |sudo -S whoami
       ss=$?
       while [ $ss -ne 0 ]
              do
              password_input=`zenity --forms  --text="Wrong password! Try again!" --title="PDMT" --add-password="Password : "`
              if [ $? -eq 1 ]
                then
                   exit
              fi
              echo $password_input |sudo -S whoami
              ss=$?
              done
fi
}

pdmt_command_maker () {
i_counter=0
for i in "$maximum_connections" "$ip" "$port" "$proxy_user" "$proxy_pass" "$download_user" "$download_pass" "$start_time" "$end_time" "$do_after_download" "$password_input" "$fname" "$referer" "$cfile" "$user_agent" "$header";do
	((i_counter ++))	
	if [ "$i" != "" ];then
		case "$i_counter" in
			"1")
			pdmt_command="$pdmt_command -m $maximum_connections"
			;;
			"2")
			pdmt_command="$pdmt_command -i $ip"
			;;
			"3")
			pdmt_command="$pdmt_command -p $port"
			;;
			"4")
			pdmt_command="$pdmt_command -u $proxy_user"
			;;
			"5")
			pdmt_command="$pdmt_command -a $proxy_pass"
			;;
			"6")
			pdmt_command="$pdmt_command -j $download_user"
			;;
			"7")
			pdmt_command="$pdmt_command -k $download_pass"
			;;
			"8")
			pdmt_command="$pdmt_command -s $start_time"
			;;
			"9")
			pdmt_command="$pdmt_command -e $end_time"
			;;
			"10")
			pdmt_command="$pdmt_command -d $do_after_download"
			;;
			"11")
			pdmt_command="$pdmt_command -w $password_input"
			;;
			"12")
			if [ "$flashgot_line" == "1" ];then
				pdmt_command="$pdmt_command -o --out=$fname"
			fi
			;;
			"13")
			pdmt_command="$pdmt_command -o --referer=\"$referer\""
			;;
			"14")
			pdmt_command="$pdmt_command -o  --load-cookies=\"$cfile\""
			;;
			"15")
			pdmt_command="$pdmt_command -o  --user-agent=\"$user_agent\""
			;;
			"16")
			pdmt_command="$pdmt_command -o  --header=\"$header\""
			;;
		esac
	fi
done

}

HOME=$(eval echo ~${USER})
export HOME

user=$HOME
temp_path="$user/.persepolis_download_manager_terminal/temp"
mkdir $temp_path       >/dev/null 2>&1

while getopts "l:c:b:g:u:h:" options ; do
case "${options}" in
    l)
    link=${OPTARG}
    ;;
    b)
    referer=${OPTARG}
    ;;
    c)
    cfile=${OPTARG}
    ;;
    g)
    fname=${OPTARG}
    ;;
    u)
    user_agent=${OPTARG}
    ;;
    h)
    header=${OPTARG}
    ;;
esac
done


fname=${fname// /_}


flashgot_status=$(cat $temp_path/flashgot.txt ) 

if [ "$flashgot_status" != "1" ]
   then
       echo "1" > $temp_path/flashgot.txt
       echo "$link" > $temp_path/flashgot_queue.txt
       sleep 2
       echo "0" > $temp_path/flashgot.txt
       flashgot_function
   else
       echo "$link" >> $temp_path/flashgot_queue.txt
       exit
fi 

for terminal in $TERMINAL x-terminal-emulator gnome-terminal xfce4-terminal lxterminal konsole mate-terminal urxvt rxvt terminator Eterm aterm roxterm termite xterm ; do
    if command -v $terminal > /dev/null 2>&1; then
        break
    fi
done

  
flashgot_line=$(cat $temp_path/flashgot_queue.txt|wc -l)
case "$flashgot_line" in
			1)
			  pdmt_command="pdmt -l \"$link\""
			  pdmt_command_maker
			  $terminal -e "$pdmt_command"
			  a=$?
			;;
			*)  
                          pdmt_command="pdmt -f $temp_path/flashgot_queue.txt"
			  pdmt_command_maker
			  $terminal -e "$pdmt_command"			
			  a=$?		
			;;
esac

			
if [ "$a" != "0" ] && [ "$a" != "255" ]
    then
	  xterm -e "$pdmt_command"
fi        
exit       
